#FROM php:5.5-fpm
FROM cespi/php-5.3:modules-fpm
#RUN apt-get update && apt-get install -y \
#	libpng-dev \
#	libzip-dev \
#	zip
#RUN docker-php-ext-configure zip
#RUN docker-php-ext-configure gd
#RUN docker-php-ext-install mysqli pdo pdo_mysql zip gd
